export default {
 
    products : [
        {
            id : '1',
            name : 'awesome hoodie - black with pictures inside - wide neck hole',
            category : 'hoodies',
            image : "../images/product1.jfif",
            price : 45,
            rating : 4.5,
            countInStock : 6,
        },
        {
            id : '2',
            name : 'red army hoodie ,half black with hat and gray in the middle ',
            category : 'hoodies',
            image : "../images/product2.jfif",
            price : 50,
            rating : 4,
            countInStock : 6,
        },
        {
            id : '3',
            name : 'fully gray hoodie for ripped niggas ,tight as hell',
            category : 'hoodies',
            image : "../images/product3.jfif",
            price : 39.99,
            rating : 3.5,
            countInStock : 6,
        },
        {
            id : '4',
            name : 'white Tshirt with drawing in middle -bcipes shown',
            category : 'tshirts',
            image : "../images/product4.jfif",
            price : 25,
            rating : 2.5,
            countInStock : 6,
        },
        {
            id : '5',
            name : 'army looking ass t-shirt ,tight with buttons -shows abs',
            category : 'tshirts',
            image : "../images/product5.jfif",
            price : 15,
            rating : 2,
            countInStock : 6,
        },
        {
            id : '6',
            name : 'tight pants -blueish color ',
            category : 'pants',
            image : "../images/product6.jfif",
            price : 30,
            rating : 3.5,
            countInStock : 6,
        },
        {
            id : '7',
            name : 'ripped jeans pants with lots of holes ',
            category : 'pants',
            image : "../images/product7.jfif",
            price : 19,
            rating : 1.5,
            countInStock : 6,
        },
        {
            id : '8',
            name : 'jeans coat ,with fur inside and long neck',
            category : 'coats',
            image : "../images/product8.jfif",
            price : 125,
            rating : 5,
            countInStock : 6,
        },
        {
            id : '9',
            name : 'fully black suit -bussiness dress with pants',
            category : 'suits',
            image : "../images/product10.jfif",
            price : 599,
            rating : 5,
            countInStock : 6,
        },
    ],
};